# PowerShell tab-completion for kanon (generated by `kanon completion powershell`).
# Evaluate in your session or PowerShell $PROFILE:
#   kanon completion powershell | Out-String | Invoke-Expression

$_kanon_subcommands = @('add', 'catalog', 'clean', 'completion', 'doctor', 'install', 'marketplace', 'search', 'list', 'outdated', 'remove', 'validate', 'repo', 'why')

Register-ArgumentCompleter -Native -CommandName 'kanon' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $_kanon_subcommands |
        Where-Object { $_ -like "$wordToComplete*" } |
        Sort-Object |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new(
                $_, $_, 'ParameterValue', $_
            )
        }
}
