#compdef kanon

# AUTOMATICALLY GENERATED by `shtab`


_shtab_kanon_commands() {
  local _commands=(
    "__complete_cached_catalogs:Internal hidden subcommand for shell completion of cached catalog identifiers."
    "__complete_catalog_entries:Internal hidden subcommand for shell completion of catalog entry names."
    "__complete_catalog_versions:Internal hidden subcommand for shell completion of catalog version tags and branches."
    "__complete_names_in_lockfile:Internal hidden subcommand for shell completion of lockfile names."
    "__complete_project_versions:Internal hidden subcommand for shell completion of project version tags and branches."
    "__complete_source_names_in_kanon:Internal hidden subcommand for shell completion of .kanon source names."
    "__resolve_entry_to_repo_url:Internal hidden subcommand for the mid-token splitter. Given a catalog entry name, returns the catalog source URL to stdout so the shell helper can route to _kanon_complete_project_versions."
    "add:Resolve catalog entries from a manifest repo and append the"
    "catalog:Subcommands for inspecting and auditing manifest repos."
    "clean:Execute the full Kanon clean lifecycle."
    "completion:Emit the shell completion script for kanon to stdout."
    "doctor:Run workspace health checks against the current project directory."
    "install:Execute the full Kanon install lifecycle."
    "marketplace:Manage the per-dependency Claude marketplace install flag in .kanon."
    "outdated:Compare each KANON_SOURCE_\<name\>_\* block in the .kanon file against"
    "remove:Remove the KANON_SOURCE_\<alias\>_\{URL,REF,PATH,NAME,GITBASE\} block for"
    "repo:Run kanon\'s repo subcommands."
    "search:Print one catalog entry name per line to stdout, sorted"
    "validate:Validate manifest XML files for well-formedness and correctness."
    "why:Reads the .kanon file, resolves the full dependency tree"
  )
  _describe 'kanon commands' _commands
}

_shtab_kanon_catalog_commands() {
  local _commands=(
    "audit:Audit a manifest repo for catalog soft-spot violations."
  )
  _describe 'kanon catalog commands' _commands
}

_shtab_kanon_marketplace_commands() {
  local _commands=(
    "disable:Remove the KANON_SOURCE_\<alias\>_MARKETPLACE line from .kanon for the"
    "enable:Write KANON_SOURCE_\<alias\>_MARKETPLACE\=true into .kanon for the"
    "status:Print a table of every dependency in .kanon, its catalog \<type\>, and"
  )
  _describe 'kanon marketplace commands' _commands
}

_shtab_kanon_validate_commands() {
  local _commands=(
    "lockfile:Check that the consumer-project .kanon declarations agree with the"
    "marketplace:Validate all marketplace XML manifests under repo-specs\/."
    "metadata:Check every \*-marketplace.xml under repo-specs\/ for in-repo soft-spot violations (spec Section 3.5 rules 1, 2, 3)."
    "xml:Validate all XML manifest files under repo-specs\/."
  )
  _describe 'kanon validate commands' _commands
}

_shtab_kanon_options=(
  {-h,--help}"[Show this and exit.]:help:"
  "(- : *)--version[show program\'s version number and exit]"
  "--quiet[Suppress all output except errors. Mutually exclusive with --verbose.]"
  "--verbose[Enable debug-level output. Mutually exclusive with --quiet.]"
  "--no-color[Disable ANSI color output. Takes precedence over the NO_COLOR environment variable and TTY auto-detection.]"
  "--no-update-check[Skip the best-effort \'update available\' PyPI lookup for this invocation. Equivalent to setting KANON_SKIP_UPDATE_CHECK\=1.]"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_defaults_added=0

_shtab_kanon___complete_cached_catalogs_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon___complete_cached_catalogs_defaults_added=0

_shtab_kanon___complete_catalog_entries_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon___complete_catalog_entries_defaults_added=0

_shtab_kanon___complete_catalog_versions_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon___complete_catalog_versions_defaults_added=0

_shtab_kanon___complete_names_in_lockfile_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon___complete_names_in_lockfile_defaults_added=0

_shtab_kanon___complete_project_versions_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Project repository URL to query for version tags and branches.:"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon___complete_project_versions_defaults_added=0

_shtab_kanon___complete_source_names_in_kanon_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Completion prefix to filter results.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon___complete_source_names_in_kanon_defaults_added=0

_shtab_kanon___resolve_entry_to_repo_url_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Catalog entry name to resolve to a repo URL.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon___resolve_entry_to_repo_url_defaults_added=0

_shtab_kanon_add_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--catalog-source[Remote catalog source as \'\<git_url\>\@\<ref\>\' where ref is a branch, tag, or \'latest\'. Overrides the KANON_CATALOG_SOURCES env var. Required when KANON_CATALOG_SOURCES configures no single source.]:catalog_source:"
  "--as[Override the auto-computed local alias for the (single) added
entry. The alias charset is \[A-Za-z0-9_\] with no \'__\' run. When
the alias is already mapped to a different source it is a hard
error (use --force to overwrite, or \'kanon remove \<alias\>\'
first). Without --as, the alias is the sanitized manifest name,
auto-suffixed deterministically on a cross-source collision.]:alias_override:"
  "--kanon-file[Destination .kanon file path. Defaults to \'.\/.kanon\'. Overridden by the KANON_KANON_FILE environment variable\; the CLI flag takes precedence when both are set.]:kanon_file:"
  "--force[Overwrite an existing alias block when re-adding the same
package (same source\@ref), and re-pin its .kanon.lock entry
while keeping the dep\'s NAME. Without this flag, a re-add of an
existing alias is a hard error (with a diff and the guiding
message). A cross-source collision (a different source for the
same manifest name) is auto-suffixed deterministically and is
never an error, with or without --force.]"
  "--dry-run[Print the diff that WOULD be written to the destination
.kanon file (\'\+\' for added lines, \'-\' for removed lines when a
--force overwrite replaces an existing block). Makes no on-disk
change. Exits 0. Alias resolution still runs first, so a
within-request duplicate or a re-add of an existing alias
(without --force) is reported before any diff is shown.]"
  "--marketplace-install[Force the added dependency to register as a Claude marketplace
(write KANON_SOURCE_\<alias\>_MARKETPLACE\=true), overriding the
auto-detected \<catalog-metadata\>\<type\>. Errors if the entry is not
a \'claude-marketplace\' type. Mutually exclusive with
--no-marketplace-install.]"
  "--no-marketplace-install[Force the added dependency to NOT register as a marketplace (omit
the KANON_SOURCE_\<alias\>_MARKETPLACE line), overriding the
auto-detected \<catalog-metadata\>\<type\>. Mutually exclusive with
--marketplace-install.]"
  "(*):One or more catalog entry names, optionally suffixed with \'\@\<spec\>\':"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_add_defaults_added=0

_shtab_kanon_catalog_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_catalog_defaults_added=0

_shtab_kanon_catalog_audit_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--check[Comma-separated list of checks to run, or \'all\' (default). Valid values\: all, entry-name-uniqueness, metadata, remote-url, source-name-derivation, tag-format. Cannot mix \'all\' with individual check names.]:check:"
  "--format[Output format. \'text\' prints one finding per line with ERROR\:\/WARN\:\/INFO\: prefix. \'json\' prints a single JSON object \{\"findings\"\: \[...\]\}. Default\: text. Env\: KANON_CATALOG_AUDIT_FORMAT.]:format:(text json)"
  "--strict[Promotes warnings to errors when enabled\; exits non-zero when any WARN-level finding is present. Prints a one-line summary to stderr naming the warning count when warnings exist.]"
  ":Path to a local manifest repo directory (must contain repo-specs\/) or a remote \'\<git_url\>\@\<ref\>\' catalog source. Defaults to \'.\' (cwd).:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_catalog_audit_defaults_added=0

_shtab_kanon_clean_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--orphans[Also unregister kanon-owned marketplaces no longer referenced by .kanon\/.kanon.lock (prunes them from \~\/.claude).]"
  ":Path to the .kanon configuration file (default\: auto-discover from current directory):"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_clean_defaults_added=0

_shtab_kanon_completion_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Target shell. Choices\: \{bash, zsh, powershell\}.:(bash zsh powershell)"
  ":Target shell. Choices\: \{bash, zsh, powershell\}.:(bash zsh powershell)"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_completion_defaults_added=0

_shtab_kanon_doctor_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--kanon-file[Path to the .kanon file that identifies the workspace root. Defaults to \'.\/.kanon\'. Overridden by the KANON_KANON_FILE environment variable\; the CLI flag takes precedence when both are set.]:kanon_file:"
  "--lock-file[Path to the .kanon.lock lockfile. Defaults to \'\<kanon-file\>.lock\' (e.g. .\/.kanon.lock). Overridden by the KANON_LOCK_FILE environment variable.]:lock_file:"
  "--strict-drift[Promote branch-drift findings from info-level to error-level. With this flag, kanon doctor returns exit code 1 when any branch-pinned source\'s tip SHA differs from the locked SHA.]"
  "--refresh-completion-cache[Subcheck 8\: invalidate the shell completion cache under \<KANON_HOME\>\/cache\/completion-cache\/. Removes all files there and recreates the directory with mode 0700. Reports an info finding with the count of files removed.]"
  "--prune-cache[Subcheck 10\: remove cache files under the KANON_HOME cache whose last-access time is older than KANON_CACHE_PRUNE_AGE_DAYS days (default 30). Reports an info finding with the count and total byte size pruned. Also reports stale .kanon-data\/.kanon-install.lock files as advisory (does not delete them).]"
  "--catalog-source[Remote catalog source as \'\<git_url\>\@\<ref\>\' where ref is a branch, tag, or \'latest\'. Overrides the KANON_CATALOG_SOURCES env var. Required when KANON_CATALOG_SOURCES configures no single source.]:catalog_source:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_doctor_defaults_added=0

_shtab_kanon_install_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--refresh-lock[Ignore the existing lockfile, re-resolve every transitive version from scratch against the committed .kanon source declarations, and overwrite .kanon.lock with the new state.]"
  "--refresh-lock-source[Re-resolve exactly one top-level source\'s full chain from the committed .kanon while preserving every other source\'s lockfile entries verbatim. NAME may be a source name (the KANON_SOURCE_\<name\> key) or a catalog entry name resolved via derive_source_name.]:refresh_lock_source:"
  "--strict-lock[Upgrade orphaned lock entries to a hard error. An orphaned lock entry is a source present in .kanon.lock but absent from .kanon (e.g. after \'kanon remove\'). Without this flag, orphaned entries are pruned and an info-line is emitted per orphan. With this flag, kanon exits with an error listing every orphaned source. Remediation\: run without --strict-lock to prune, or restore the missing KANON_SOURCE_\<name\>_\* triples in .kanon.]"
  "--strict-drift[Upgrade branch drift to a hard error. Branch drift occurs when the lockfile records a SHA for a branch-shaped source but the branch\'s current tip on the remote is a different SHA. Without this flag, the locked SHA is reused and an info-line is emitted. With this flag, kanon exits with an error listing every drifted source. Remediation\: run \'kanon install --refresh-lock-source \<source\>\' to accept the new branch tip.]"
  "--lock-file[Path to the lock file. Defaults to \<kanon-file\>.lock (derived from --kanon-file). The KANON_LOCK_FILE environment variable is consulted when this flag is absent\; the CLI flag takes precedence when both are set.]:lock_file:"
  ":Path to the .kanon configuration file (default\: auto-discover from current directory):"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_install_defaults_added=0

_shtab_kanon_marketplace_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_marketplace_defaults_added=0

_shtab_kanon_marketplace_disable_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--kanon-file[Path to the .kanon file to read\/modify. Defaults to \'.\/.kanon\'. Overridden by the KANON_KANON_FILE environment variable\; the CLI flag takes precedence when both are set.]:kanon_file:"
  ":The source alias to disable (canonical alias or original entry name).:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_marketplace_disable_defaults_added=0

_shtab_kanon_marketplace_enable_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--kanon-file[Path to the .kanon file to read\/modify. Defaults to \'.\/.kanon\'. Overridden by the KANON_KANON_FILE environment variable\; the CLI flag takes precedence when both are set.]:kanon_file:"
  ":The source alias to enable (canonical alias or original entry name).:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_marketplace_enable_defaults_added=0

_shtab_kanon_marketplace_status_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--all[Show every dependency, including those that are not a marketplace
type. Without --all, only marketplace-typed dependencies are listed.]"
  "--kanon-file[Path to the .kanon file to read\/modify. Defaults to \'.\/.kanon\'. Overridden by the KANON_KANON_FILE environment variable\; the CLI flag takes precedence when both are set.]:kanon_file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_marketplace_status_defaults_added=0

_shtab_kanon_outdated_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--catalog-source[Remote catalog source as \'\<git_url\>\@\<ref\>\' where ref is a branch, tag, or \'latest\'. Overrides the KANON_CATALOG_SOURCES env var. Required when KANON_CATALOG_SOURCES configures no single source.]:catalog_source:"
  "--kanon-file[Path to the .kanon file. Defaults to \'.\/.kanon\'. Overridden by the KANON_KANON_FILE environment variable\; the CLI flag takes precedence when both are set.]:kanon_file:"
  "--lock-file[Path to the .kanon.lock file. When present, provides the current resolved SHA. When absent, the command live-resolves against the catalog. Defaults to \<kanon-file\>.lock. Overridden by the KANON_LOCK_FILE environment variable\; the CLI flag takes precedence when both are set.]:lock_file:"
  "--fail-on-upgrade[Exit 1 when ANY source has an available upgrade (upgrade-type \!\= \'none\'). Default is to always exit 0 (parity with pip list --outdated, npm outdated, cargo outdated). Use this flag in CI pipelines to gate on lockfile freshness\: the build fails when any source is upgradable, prompting the operator to refresh the lockfile. Spec reference\: spec\/kanon-list-add-lock-features-spec.md Section 0.2 and Section 4.4 \'Exit code\'.]"
  "--format[Output format\: \'table\' (default) or \'json\'. The \'json\' format emits a top-level array of objects, one per source, with keys\: name, current, latest-matching-spec, latest-available, upgrade-type. Overridden by the KANON_OUTDATED_FORMAT environment variable\; the CLI flag takes precedence when both are set.]:format:(table json)"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_outdated_defaults_added=0

_shtab_kanon_remove_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--kanon-file[Path to the .kanon file to modify. Defaults to \'.\/.kanon\'. Overridden by the KANON_KANON_FILE environment variable\; the CLI flag takes precedence when both are set.]:kanon_file:"
  "--force[Silently skip sources that are not fully present in the .kanon file (used to clean up partially-orphaned entries). Known sources are still removed atomically.]"
  "--dry-run[Preview mode\: shows which lines would be removed. Each removed line is
printed to stdout with a \'-\' prefix. Makes no on-disk change. Exits 0.
The file-writing rules (line-ending preservation, blank-run collapse,
trailing-newline normalisation) apply only to the normal write path,
not to the dry-run output.]"
  "(*):One or more source aliases to remove. Each may be the canonical alias:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_remove_defaults_added=0

_shtab_kanon_repo_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--repo-dir[Path to the .repo directory for the repo tool (default\: \$\{KANON_REPO_DIR\} or \'.repo\')]:repo_dir:"
  "(-)*:Arguments forwarded verbatim to the repo tool:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_repo_defaults_added=0

_shtab_kanon_search_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "*--catalog-source[Remote catalog source as \'\<git_url\>\@\<ref\>\' where ref is a branch, tag, or \'latest\'. Overrides the KANON_CATALOG_SOURCES env var. Required when KANON_CATALOG_SOURCES configures no single source. May be repeated to search several sources\; the supplied flags fully replace KANON_CATALOG_SOURCES for this invocation.]:catalog_source:"
  "--format[Output format. \'names\' (default)\: one entry name per line, pipeable into kanon add. \'json\'\: structured JSON array. Default mode and --detail mode emit \{name, display-name, type, description, version\} objects\; -A\/--all mode emits \{name, version, ref, sha\} objects. The KANON_LIST_FORMAT environment variable sets the format when this flag is absent\; the CLI flag takes precedence when both are set. --format json is incompatible with --tree (hard error at validation time).]:list_format:(names json)"
  "--detail[Print a human-readable multi-line record per entry (display-name, description, version, type). Human-readable only -- not pipeable into kanon add. For machine consumers, combine with --format json.]"
  "--tree[Render a three-layer ASCII dependency tree per entry\: the catalog entry (root), the XML manifests reachable via transitive \<include\> directives, and the \<project\> repos referenced by those manifests. Each node shows the version resolved at command-execution time. Mutually exclusive with -A\/--all. Subject to the threshold guardrail (KANON_TREE_NO_FILTER_THRESHOLD, default 20)\: when the catalog exceeds the threshold, supply a filter -- positional substring, --regex, --max-depth 0 -- or pass --no-filter-required.]"
  "--max-depth[Cap the tree depth rendered by --tree. 0 \= root entry node only (no XML or project layers). 1 \= root \+ XML layer only. Default\: unlimited. --max-depth 0 also satisfies the threshold guardrail as a valid filter.]:max_depth:"
  "--no-filter-required[Bypass the threshold guardrail for --tree. Normally, catalogs with more than KANON_TREE_NO_FILTER_THRESHOLD (default 20) entries require a filter (positional substring, --regex, or --max-depth 0) to avoid accidental full-catalog tree renders. Pass this flag to bypass the check.]"
  {-A,--all}"[Show all tagged versions of each matching manifest instead of the latest-only default. Walks all historical tagged versions of the manifest repo and emits one \<name\>\@\<version\> row per catalog entry per version. Versions are ordered newest-first by PEP 440 natural sort\; entries within each version are sorted lexicographically. Mutually exclusive with --tree. Default cap\: KANON_LIST_LIMIT (default 50, overridable via env var). Use --limit N or --no-limit to control the number of versions walked.]"
  "--limit[Cap the number of versions walked by -A\/--all. Default\: KANON_LIST_LIMIT (default 50, overridable via the KANON_LIST_LIMIT environment variable). Mutually exclusive with --no-limit.]:limit:"
  "--no-limit[Walk all PEP 440-valid tags when using -A\/--all, with no cap. Equivalent to --limit \<very-large-number\>. Mutually exclusive with --limit.]"
  "--since-version[Filter the versions walked by -A\/--all to those matching a PEP 440 specifier constraint (e.g. \'\>\=1.0,\<2.0\'). The constraint is evaluated against the PEP 440 version parsed from each tag name. Tags that do not parse as PEP 440 are skipped. Example\: --since-version \'\>\=1.0,\<2.0\']:since_version:"
  "--regex[Regular-expression filter (Python re.search). When supplied, only entries whose name, display-name, description, or keywords match the pattern are returned. The keywords field matches when any element satisfies re.search. Mutually exclusive with the positional \<substring\>. Use --match-fields to restrict the fields checked. Example\: --regex \'\^foo\']:regex:"
  "--match-fields[Comma-separated list of fields to check when filtering. Legal values\: name, display-name, description, keywords. Default (when --match-fields is not supplied)\: all four fields. Requires the positional \<substring\> or --regex to be present\; supplying --match-fields without a filter is a hard error. Example\: --match-fields keywords]:match_fields:"
  ":Optional case-sensitive substring filter. When supplied, only entries whose name, display-name, description, or keywords contain the substring are returned. Mutually exclusive with --regex. Use --match-fields to restrict the fields checked.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_search_defaults_added=0

_shtab_kanon_validate_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_validate_defaults_added=0

_shtab_kanon_validate_lockfile_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--lock-file[Path to the lock file. Defaults to \<kanon-file\>.lock (derived from the .kanon path). The KANON_LOCK_FILE environment variable is consulted when this flag is absent\; the CLI flag takes precedence when both are set.]:lock_file:"
  ":Path to the .kanon configuration file (default\: auto-discover from current directory):"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_validate_lockfile_defaults_added=0

_shtab_kanon_validate_marketplace_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--repo-root[Repository root directory (default\: auto-detect via git rev-parse)]:repo_root:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_validate_marketplace_defaults_added=0

_shtab_kanon_validate_metadata_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--repo-root[Repository root directory (default\: auto-detect via git rev-parse)]:repo_root:"
  "--format[Output format. \'text\' prints one finding per line with ERROR\:\/WARN\:\/INFO\: prefix. \'json\' prints a single JSON object \{\"findings\"\: \[...\]\}. Default\: text.]:format:(text json)"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_validate_metadata_defaults_added=0

_shtab_kanon_validate_xml_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--repo-root[Repository root directory (default\: auto-detect via git rev-parse)]:repo_root:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_validate_xml_defaults_added=0

_shtab_kanon_why_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--catalog-source[Remote catalog source as \'\<git_url\>\@\<ref\>\' where ref is a branch, tag, or \'latest\'. Overrides the KANON_CATALOG_SOURCES env var. Required when KANON_CATALOG_SOURCES configures no single source.]:catalog_source:"
  "--kanon-file[Path to the .kanon file. Defaults to \'.\/.kanon\'. Overridden by the KANON_KANON_FILE environment variable\; the CLI flag takes precedence when both are set.]:kanon_file:"
  "--lock-file[Path to the .kanon.lock file. When present, the tree is built from lockfile entries (no git calls). When absent, the command live-resolves against the catalog. Defaults to \<kanon-file\>.lock. Overridden by the KANON_LOCK_FILE environment variable\; the CLI flag takes precedence when both are set.]:lock_file:"
  "--format[Output format\: \'text\' (default) or \'json\'. Overridden by the KANON_WHY_FORMAT environment variable\; the CLI flag takes precedence when both are set.]:format:(text json)"
  ":The project URL, XML manifest path, or source name to look up. Project URLs are canonicalized via canonicalize_repo_url before matching. XML manifest paths are matched by exact string equality. Source names are normalized via derive_source_name (case- and separator-insensitive).:"
)

# guard to ensure default positional specs are added only once per session
_shtab_kanon_why_defaults_added=0


_shtab_kanon() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->kanon'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_kanon_defaults_added )); then
    if (( ${_shtab_kanon_options[(I)${(q)one_or_more}*]} +          ${_shtab_kanon_options[(I)${(q)remainder}*]} +          ${_shtab_kanon_options[(I)${(q)default}]} == 0 )); then
      _shtab_kanon_options+=(': :_shtab_kanon_commands' '*::: :->kanon')
    fi
    _shtab_kanon_defaults_added=1
  fi
  _arguments -C -s $_shtab_kanon_options

  case $state in
    kanon)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_kanon-$line[1]:"
      case $line[1] in
        __complete_cached_catalogs) _arguments -C -s $_shtab_kanon___complete_cached_catalogs_options ;;
        __complete_catalog_entries) _arguments -C -s $_shtab_kanon___complete_catalog_entries_options ;;
        __complete_catalog_versions) _arguments -C -s $_shtab_kanon___complete_catalog_versions_options ;;
        __complete_names_in_lockfile) _arguments -C -s $_shtab_kanon___complete_names_in_lockfile_options ;;
        __complete_project_versions) _arguments -C -s $_shtab_kanon___complete_project_versions_options ;;
        __complete_source_names_in_kanon) _arguments -C -s $_shtab_kanon___complete_source_names_in_kanon_options ;;
        __resolve_entry_to_repo_url) _arguments -C -s $_shtab_kanon___resolve_entry_to_repo_url_options ;;
        add) _arguments -C -s $_shtab_kanon_add_options ;;
        catalog) _shtab_kanon_catalog ;;
        clean) _arguments -C -s $_shtab_kanon_clean_options ;;
        completion) _arguments -C -s $_shtab_kanon_completion_options ;;
        doctor) _arguments -C -s $_shtab_kanon_doctor_options ;;
        install) _arguments -C -s $_shtab_kanon_install_options ;;
        marketplace) _shtab_kanon_marketplace ;;
        outdated) _arguments -C -s $_shtab_kanon_outdated_options ;;
        remove) _arguments -C -s $_shtab_kanon_remove_options ;;
        repo) _arguments -C -s $_shtab_kanon_repo_options ;;
        search) _arguments -C -s $_shtab_kanon_search_options ;;
        validate) _shtab_kanon_validate ;;
        why) _arguments -C -s $_shtab_kanon_why_options ;;
      esac
  esac
}

_shtab_kanon_catalog() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->catalog'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_kanon_catalog_defaults_added )); then
    if (( ${_shtab_kanon_catalog_options[(I)${(q)one_or_more}*]} +          ${_shtab_kanon_catalog_options[(I)${(q)remainder}*]} +          ${_shtab_kanon_catalog_options[(I)${(q)default}]} == 0 )); then
      _shtab_kanon_catalog_options+=(': :_shtab_kanon_catalog_commands' '*::: :->catalog')
    fi
    _shtab_kanon_catalog_defaults_added=1
  fi
  _arguments -C -s $_shtab_kanon_catalog_options

  case $state in
    catalog)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_kanon_catalog-$line[1]:"
      case $line[1] in
        audit) _arguments -C -s $_shtab_kanon_catalog_audit_options ;;
      esac
  esac
}

_shtab_kanon_marketplace() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->marketplace'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_kanon_marketplace_defaults_added )); then
    if (( ${_shtab_kanon_marketplace_options[(I)${(q)one_or_more}*]} +          ${_shtab_kanon_marketplace_options[(I)${(q)remainder}*]} +          ${_shtab_kanon_marketplace_options[(I)${(q)default}]} == 0 )); then
      _shtab_kanon_marketplace_options+=(': :_shtab_kanon_marketplace_commands' '*::: :->marketplace')
    fi
    _shtab_kanon_marketplace_defaults_added=1
  fi
  _arguments -C -s $_shtab_kanon_marketplace_options

  case $state in
    marketplace)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_kanon_marketplace-$line[1]:"
      case $line[1] in
        disable) _arguments -C -s $_shtab_kanon_marketplace_disable_options ;;
        enable) _arguments -C -s $_shtab_kanon_marketplace_enable_options ;;
        status) _arguments -C -s $_shtab_kanon_marketplace_status_options ;;
      esac
  esac
}

_shtab_kanon_validate() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->validate'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_kanon_validate_defaults_added )); then
    if (( ${_shtab_kanon_validate_options[(I)${(q)one_or_more}*]} +          ${_shtab_kanon_validate_options[(I)${(q)remainder}*]} +          ${_shtab_kanon_validate_options[(I)${(q)default}]} == 0 )); then
      _shtab_kanon_validate_options+=(': :_shtab_kanon_validate_commands' '*::: :->validate')
    fi
    _shtab_kanon_validate_defaults_added=1
  fi
  _arguments -C -s $_shtab_kanon_validate_options

  case $state in
    validate)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_kanon_validate-$line[1]:"
      case $line[1] in
        lockfile) _arguments -C -s $_shtab_kanon_validate_lockfile_options ;;
        marketplace) _arguments -C -s $_shtab_kanon_validate_marketplace_options ;;
        metadata) _arguments -C -s $_shtab_kanon_validate_metadata_options ;;
        xml) _arguments -C -s $_shtab_kanon_validate_xml_options ;;
      esac
  esac
}

# Custom Preamble

# kanon shell-completion preamble (zsh)
# Sourced by the generated completion script produced by `kanon completion zsh`.

# _kanon_run_complete <subcommand> [args...]
#
# Common dispatcher called by every named helper.
# Respects KANON_COMPLETION_ENABLED and KANON_COMPLETION_TIMEOUT.
_kanon_run_complete() {
    local _subcommand="$1"
    shift
    # Honour KANON_COMPLETION_ENABLED (default 1 = enabled).
    if [[ "${KANON_COMPLETION_ENABLED:-1}" == "0" ]]; then
        return 0
    fi
    local _timeout="${KANON_COMPLETION_TIMEOUT:-2}"
    local -a _lines
    if command -v timeout > /dev/null 2>&1; then
        _lines=("${(@f)$(timeout "$_timeout" kanon "$_subcommand" "$@" 2>/dev/null)}")
    else
        _lines=("${(@f)$(kanon "$_subcommand" "$@" 2>/dev/null)}")
    fi
    # Filter empty lines that result from trailing newlines in subprocess output.
    local -a _candidates
    local _item
    for _item in "${_lines[@]}"; do
        [[ -n "$_item" ]] && _candidates+=("$_item")
    done
    [[ ${#_candidates[@]} -gt 0 ]] && compadd -- "${_candidates[@]}"
}

_kanon_complete_catalog_entries() {
    local cur="${1:-}"
    _kanon_run_complete __complete_catalog_entries "$cur"
}

_kanon_complete_source_names_in_kanon() {
    local cur="${1:-}"
    _kanon_run_complete __complete_source_names_in_kanon "$cur"
}

_kanon_complete_names_in_lockfile() {
    local cur="${1:-}"
    _kanon_run_complete __complete_names_in_lockfile "$cur"
}

_kanon_complete_catalog_versions() {
    local cur="${1:-}"
    _kanon_run_complete __complete_catalog_versions "$cur"
}

_kanon_complete_project_versions() {
    local repo_url="${1:-}"
    local cur="${2:-}"
    _kanon_run_complete __complete_project_versions "$repo_url" "$cur"
}

_kanon_complete_cached_catalogs() {
    local cur="${1:-}"
    _kanon_run_complete __complete_cached_catalogs "$cur"
}

# _kanon_complete_add_arg -- mid-token splitter helper.
#
# Implements spec Section 11.5: detects the @ separator and routes to the
# appropriate completer. Splits on the LAST @ (spec Section 4.0).
#
# When KANON_COMPLETION_ENABLED=0, returns immediately without shelling out
# to kanon __resolve_entry_to_repo_url.
_kanon_complete_add_arg() {
    local cur="${1:-}"
    # Honour KANON_COMPLETION_ENABLED (default 1 = enabled).
    if [[ "${KANON_COMPLETION_ENABLED:-1}" == "0" ]]; then
        return 0
    fi
    if [[ "$cur" == *@* ]]; then
        # Split on the LAST @ per spec Section 4.0.
        local _name="${cur%@*}"
        local _spec="${cur##*@}"
        local _repo_url
        local _timeout="${KANON_COMPLETION_TIMEOUT:-2}"
        if command -v timeout > /dev/null 2>&1; then
            _repo_url=$(timeout "$_timeout" kanon __resolve_entry_to_repo_url "$_name" 2>/dev/null) || return 0
        else
            _repo_url=$(kanon __resolve_entry_to_repo_url "$_name" 2>/dev/null) || return 0
        fi
        [[ -z "$_repo_url" ]] && return 0
        _kanon_complete_project_versions "$_repo_url" "$_spec"
    else
        _kanon_complete_catalog_entries "$cur"
    fi
}

# End Custom Preamble


typeset -A opt_args

if [[ $zsh_eval_context[-1] == eval ]]; then
  # eval/source/. command, register function for later
  compdef _shtab_kanon -N kanon
else
  # autoload from fpath, call function directly
  _shtab_kanon "$@"
fi
