"""kanon completion subcommand: emit a shell completion script to stdout.

Usage:
  kanon completion bash   -- print the bash completion script
  kanon completion zsh    -- print the zsh completion script

The script is generated by shtab from the kanon root ArgumentParser.
Pipe the output to a file and source it in your shell's rc file, or
install it into the shell's completion directory:

  kanon completion bash > /etc/bash_completion.d/kanon
  kanon completion zsh  > "${fpath[1]}/_kanon"

Spec reference: spec/kanon-list-add-lock-features-spec.md
  Section 11.1 -- subcommand contract
  Section 11.2 -- completion coverage matrix (static enum, choices bash/zsh)
  Section 11.9 -- acceptance item 2 (generated scripts pass bash -n / zsh -n)
"""

from __future__ import annotations

import argparse
import sys

import shtab

from kanon_cli.completions.preamble import PREAMBLE

# Valid shell choices -- extending this set requires a matching PREAMBLE entry.
SUPPORTED_SHELLS: list[str] = ["bash", "zsh"]


def register(subparsers: "argparse._SubParsersAction[argparse.ArgumentParser]") -> None:
    """Register the 'completion' subcommand on the top-level argparse subparsers.

    Args:
        subparsers: The subparsers action from the top-level parser.
    """
    parser: argparse.ArgumentParser = subparsers.add_parser(
        "completion",
        add_help=True,
        help="Print a shell completion script to stdout.",
        description=(
            "Emit the shell completion script for kanon to stdout.\n\n"
            "Pipe the output to the appropriate location for your shell:\n\n"
            "  kanon completion bash > /etc/bash_completion.d/kanon\n"
            '  kanon completion zsh  > "${fpath[1]}/_kanon"\n\n'
            "Then restart your shell or re-source the completion file.\n\n"
            "See docs/shell-completion.md for full installation instructions."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "shell",
        choices=SUPPORTED_SHELLS,
        metavar="<shell>",
        help=f"Target shell. Choices: {{{', '.join(SUPPORTED_SHELLS)}}}.",
    )
    parser.set_defaults(func=handle)


def handle(args: argparse.Namespace) -> None:
    """Handle the 'completion' subcommand: write the completion script to stdout.

    Calls shtab.complete() with the root kanon ArgumentParser and the PREAMBLE
    dict from kanon_cli.completions.preamble. The generated script is written
    verbatim to stdout; stderr is left untouched on success.

    Args:
        args: Parsed arguments. Must contain:
              - args.shell (str): one of the SUPPORTED_SHELLS values
              - args.parser (argparse.ArgumentParser): the root kanon parser
                injected at invocation time from cli.py
    """
    # Retrieve the root parser injected by cli.py so shtab can introspect
    # every registered subcommand.
    root_parser: argparse.ArgumentParser = args.parser
    sys.stdout.write(shtab.complete(root_parser, args.shell, preamble=PREAMBLE))
