"""PowerShell tab-completion generator for kanon (spec Section 4.6 / FR-31).

shtab (the generator used for bash and zsh) does not support PowerShell, so
this module emits a native PowerShell completion script directly. The script
registers an argument completer for the ``kanon`` command via
``Register-ArgumentCompleter`` and offers static completion of every top-level
subcommand registered on the root :class:`argparse.ArgumentParser` (including
the ``search`` subcommand introduced by E3).

The generator introspects the injected root parser rather than hard-coding the
subcommand list, so any subcommand added to the CLI is covered automatically.
Hidden internal helper subcommands (those whose name begins with ``__``, e.g.
``__complete_catalog_entries``) are excluded from the user-facing completion
list, matching the visibility of the documented public command surface.

Windows cmd.exe has no programmable tab-completion mechanism, so cmd is a
documented gap rather than a supported completion shell (FR-39); see
``docs/shell-completion.md``.
"""

from __future__ import annotations

import argparse


def _public_subcommand_names(
    root_parser: argparse.ArgumentParser,
) -> list[str]:
    """Return the user-facing top-level subcommand names from the root parser.

    Introspects the subparsers action on ``root_parser`` and returns its
    registered choice names with hidden internal helpers (names beginning with
    ``__``) removed. Order follows the parser's registration order so the
    generated script is deterministic for a given parser.

    Args:
        root_parser: The root kanon :class:`argparse.ArgumentParser`. It must
            have a registered subparsers action (the kanon CLI always does).

    Returns:
        The public subcommand names, in registration order.

    Raises:
        ValueError: If ``root_parser`` has no subparsers action. This is a
            programming error (the kanon root parser always registers one) and
            must fail loudly rather than emit an empty completer.
    """
    for action in root_parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return [name for name in action.choices if not name.startswith("__")]
    raise ValueError(
        "ERROR: cannot build PowerShell completion: the root parser "
        f"{root_parser.prog!r} has no subparsers action to introspect.\n"
        "This is a programming error in the kanon CLI parser construction."
    )


def generate(root_parser: argparse.ArgumentParser) -> str:
    """Generate a PowerShell tab-completion script for the kanon CLI.

    Emits a ``Register-ArgumentCompleter`` block keyed on the root parser's
    program name (``root_parser.prog``) that completes the program's top-level
    subcommands. The subcommand list is derived from the injected parser via
    :func:`_public_subcommand_names`, so every registered public subcommand
    (including ``search``) is covered without hard-coding.

    Args:
        root_parser: The root kanon :class:`argparse.ArgumentParser`, injected
            by ``cli.py`` so the completer reflects the full subcommand tree.

    Returns:
        A complete PowerShell script (ending with a trailing newline) that, when
        evaluated, registers a kanon argument completer in the current session.
    """
    program: str = root_parser.prog
    subcommands: list[str] = _public_subcommand_names(root_parser)

    # PowerShell single-quoted strings escape a literal single quote by doubling
    # it. Apply that escape so a subcommand or program name containing a quote
    # cannot break out of the emitted string literal.
    def _ps_single_quote(value: str) -> str:
        return "'" + value.replace("'", "''") + "'"

    command_list: str = ", ".join(_ps_single_quote(name) for name in subcommands)
    quoted_program: str = _ps_single_quote(program)

    return (
        f"# PowerShell tab-completion for {program} (generated by "
        f"`{program} completion powershell`).\n"
        "# Evaluate in your session or PowerShell $PROFILE:\n"
        f"#   {program} completion powershell | Out-String | Invoke-Expression\n"
        "\n"
        f"$_{program}_subcommands = @({command_list})\n"
        "\n"
        f"Register-ArgumentCompleter -Native -CommandName {quoted_program} "
        "-ScriptBlock {\n"
        "    param($wordToComplete, $commandAst, $cursorPosition)\n"
        f"    $_{program}_subcommands |\n"
        '        Where-Object { $_ -like "$wordToComplete*" } |\n'
        "        Sort-Object |\n"
        "        ForEach-Object {\n"
        "            [System.Management.Automation.CompletionResult]::new(\n"
        "                $_, $_, 'ParameterValue', $_\n"
        "            )\n"
        "        }\n"
        "}\n"
    )
